{{- if .Values.crds.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "googlecasclusterissuers.cas-issuer.jetstack.io"
  {{- if .Values.crds.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "cert-manager-google-cas-issuer.labels" . | nindent 4 }}
spec:
  group: cas-issuer.jetstack.io
  names:
    kind: GoogleCASClusterIssuer
    listKind: GoogleCASClusterIssuerList
    plural: googlecasclusterissuers
    singular: googlecasclusterissuer
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=='Ready')].status
          name: ready
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].reason
          name: reason
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].message
          name: message
          type: string
      name: v1beta1
      schema:
        openAPIV3Schema:
          description: GoogleCASClusterIssuer is the Schema for the googlecasclusterissuers API
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: GoogleCASIssuerSpec defines the desired state of GoogleCASIssuer
              properties:
                caPoolId:
                  description: CaPoolId is the id of the CA pool to issue certificates from
                  type: string
                certificateAuthorityId:
                  description: |-
                    CertificateAuthorityId is specific certificate authority to
                    use to sign. Omit in order to load balance across all CAs
                    in the pool
                  type: string
                certificateTemplate:
                  description: |-
                    CertificateTemplate is specific certificate template to
                    use. Omit to not specify a template
                  type: string
                credentials:
                  description: Credentials is a reference to a Kubernetes Secret Key that contains Google Service Account Credentials
                  properties:
                    key:
                      description: |-
                        The key of the entry in the Secret resource's `data` field to be used.
                        Some instances of this field may be defaulted, in others it may be
                        required.
                      type: string
                    name:
                      description: |-
                        Name of the resource being referred to.
                        More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      type: string
                  required:
                    - name
                  type: object
                location:
                  description: Location is the Google Cloud Project Location
                  type: string
                project:
                  description: Project is the Google Cloud Project ID
                  type: string
              type: object
            status:
              properties:
                conditions:
                  description: |-
                    List of status conditions to indicate the status of an Issuer.
                    Known condition types are `Ready`.
                  items:
                    description: IssuerCondition contains condition information for an Issuer.
                    properties:
                      lastTransitionTime:
                        description: |-
                          LastTransitionTime is the timestamp corresponding to the last status
                          change of this condition.
                        format: date-time
                        type: string
                      message:
                        description: |-
                          Message is a human readable description of the details of the last
                          transition, complementing reason.
                        type: string
                      observedGeneration:
                        description: |-
                          If set, this represents the .metadata.generation that the condition was
                          set based upon.
                          For instance, if .metadata.generation is currently 12, but the
                          .status.condition[x].observedGeneration is 9, the condition is out of date
                          with respect to the current state of the Issuer.
                        format: int64
                        type: integer
                      reason:
                        description: |-
                          Reason is a brief machine readable explanation for the condition's last
                          transition.
                        type: string
                      status:
                        description: Status of the condition, one of (`True`, `False`, `Unknown`).
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                        type: string
                      type:
                        description: Type of the condition, known values are (`Ready`).
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
{{- end }}