
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: googlecasissuers.cas-issuer.jetstack.io
spec:
  group: cas-issuer.jetstack.io
  names:
    kind: GoogleCASIssuer
    listKind: GoogleCASIssuerList
    plural: googlecasissuers
    singular: googlecasissuer
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: ready
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: reason
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].message
      name: message
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GoogleCASIssuer is the Schema for the googlecasissuers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GoogleCASIssuerSpec defines the desired state of GoogleCASIssuer
            properties:
              certificateAuthorityID:
                description: CertificateAuthorityID is The ID of the Google Private certificate authority that will sign certificates
                type: string
              credentials:
                description: Credentials is a reference to a Kubernetes Secret Key that contains Google Service Account Credentials
                properties:
                  key:
                    description: The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be defaulted, in others it may be required.
                    type: string
                  name:
                    description: 'Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                required:
                - name
                type: object
              location:
                description: Location is the Google Cloud Project Location
                type: string
              project:
                description: Project is the Google Cloud Project ID
                type: string
            type: object
          status:
            description: GoogleCASIssuerStatus defines the observed state of GoogleCASIssuer
            properties:
              conditions:
                items:
                  description: IssuerCondition contains condition information for a CAS Issuer.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the timestamp corresponding to the last status change of this condition.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human readable description of the details of the last transition, complementing reason.
                      type: string
                    reason:
                      description: Reason is a brief machine readable explanation for the condition's last transition.
                      type: string
                    status:
                      allOf:
                      - enum:
                        - "True"
                        - "False"
                        - Unknown
                      - enum:
                        - "True"
                        - "False"
                        - Unknown
                      description: Status of the condition, one of ('True', 'False', 'Unknown').
                      type: string
                    type:
                      description: Type of the condition, currently ('Ready').
                      enum:
                      - Ready
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
