
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: googlecasclusterissuers.issuers.jetstack.io
spec:
  group: issuers.jetstack.io
  names:
    kind: GoogleCASClusterIssuer
    listKind: GoogleCASClusterIssuerList
    plural: googlecasclusterissuers
    singular: googlecasclusterissuer
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: GoogleCASClusterIssuer is the Schema for the googlecasclusterissuers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GoogleCASClusterIssuerSpec defines the desired state of GoogleCASClusterIssuer
          properties:
            certificateAuthorityID:
              description: CertificateAuthorityID is The ID of the Google Private
                certificate authority that will sign certificates
              type: string
            credentials:
              description: Credentials is a reference to a Kubernetes Secret Key that
                contains Google Service Account Credentials
              properties:
                key:
                  description: The key of the secret to select from. Must be a valid
                    secret key.
                  type: string
                name:
                  description: The name of the secret in the given namespace to select
                    from.
                  type: string
                namespace:
                  description: The Namespace in which to get the secret
                  type: string
              type: object
            location:
              description: Location is the Google Cloud Project Location
              type: string
            project:
              description: Project is the Google Cloud Project ID
              type: string
          type: object
        status:
          description: GoogleCASClusterIssuerStatus defines the observed state of
            GoogleCASClusterIssuer
          properties:
            conditions:
              items:
                description: IssuerCondition contains condition information for a
                  CAS Issuer.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the timestamp corresponding
                      to the last status change of this condition.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human readable description of the details
                      of the last transition, complementing reason.
                    type: string
                  reason:
                    description: Reason is a brief machine readable explanation for
                      the condition's last transition.
                    type: string
                  status:
                    allOf:
                    - enum:
                      - "True"
                      - "False"
                      - Unknown
                    - enum:
                      - "True"
                      - "False"
                      - Unknown
                    description: Status of the condition, one of ('True', 'False',
                      'Unknown').
                    type: string
                  type:
                    description: Type of the condition, currently ('Ready').
                    enum:
                    - Ready
                    type: string
                required:
                - status
                - type
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
